INSERT INTO user (first_name, last_name, email, password) VALUES ('Roxana' , 'Portillo', 'roxy4@gmail.com', 'password');
INSERT INTO user (first_name, last_name, email, password) VALUES ('Esperanza' , 'Salguero', 'esalguero4@gmail.com', '1234');
INSERT INTO user (first_name, last_name, email, password) VALUES ('Jane', 'Doe', 'janedoe4@gmail.com', '1234');
INSERT INTO user (first_name, last_name, email, password) VALUES ('John', 'Smith', 'jsmith4@gmail.com', 'password');
INSERT INTO country (name) VALUES ('El Salvador');
INSERT INTO country (name) VALUES ('United States');
INSERT INTO country (name) VALUES ('Guatemala');
INSERT INTO state (name, country_id) VALUES ('San Salvador', 1);
INSERT INTO state (name, country_id) VALUES ('California', 2);
INSERT INTO state (name, country_id) VALUES ('La Libertad', 1);
INSERT INTO city (name, state_id) VALUES ('San Salvador', 1);
INSERT INTO city (name, state_id) VALUES ('Los Angeles', 2);
INSERT INTO city (name, state_id) VALUES ('Santa Tecla', 3);
INSERT INTO address (address1, country_id, state_id, city_id, user_id) VALUES ('Col. Los Pinos Calle C #23', 1, 1, 1, 1);
INSERT INTO address (address1, country_id, state_id, city_id, user_id) VALUES ('12 Cross St', 2, 2, 2, 2);
INSERT INTO address (address1, country_id, state_id, city_id, user_id) VALUES ('Villa Nueva Calle 14 #5', 3, 3, 3, 3);
INSERT INTO address (address1, country_id, state_id, city_id, user_id) VALUES ('Col. MonteVerde Calle 10 #2', 1, 3, 3, 1);
INSERT INTO credit_card (number, cvv, balance, exp_date, user_id) VALUES ('4177581972590838', '345', 500.00, '2027-05-01', 1);
INSERT INTO credit_card (number, cvv, balance, exp_date, user_id) VALUES ('370353444701192', '678', 100.25, '2024-07-01', 1);
INSERT INTO credit_card (number, cvv, balance, exp_date, user_id) VALUES ('4177587700326296', '789', 224.50, '2024-02-01', 2);
INSERT INTO credit_card (number, cvv, balance, exp_date, user_id) VALUES ('4177588202116151', '556', 80.98, '2026-05-01', 3);
INSERT INTO credit_card (number, cvv, balance, exp_date, user_id) VALUES ('4177584140545155', '726', 150.50, '2030-03-01', 3);
INSERT INTO product (name, price, stock, category_id) VALUES ('Desk Lamp', 24.99, 59, 1);
INSERT INTO product (name, price, stock, category_id) VALUES ('Basic Black T-Shirt', 12.00, 46, 2);
INSERT INTO product (name, price, stock, category_id) VALUES ('Wireless Headphones', 59.99, 23, 3);
INSERT INTO product (name, price, stock, category_id) VALUES ('Wood Table', 12.50, 45, 1);
INSERT INTO product (name, price, stock, category_id) VALUES ('Cotton Socks', 3.45, 57, 2);
INSERT INTO product (name, price, stock, category_id) VALUES ('USB Cable', 2.50, 101, 3);
INSERT INTO product (name, price, stock, category_id) VALUES ('Polyester Carpet', 45.99, 15, 1);
INSERT INTO product (name, price, stock, category_id) VALUES ('Blue Jeans', 9.99, 28, 2);
INSERT INTO product (name, price, stock, category_id) VALUES ('Jean Jacket', 20.00, 89, 2);
INSERT INTO product (name, price, stock, category_id) VALUES ('Phone Charger', 7.88, 23, 3);
